### ISSUE TITLE
Передача картинки без создания файла

### ISSUE THREAD

**Issue by FrCln** [Pygame-Tetris-2020/tetris-2020#12]
В файле `stat_hist.py` нужно вместо сохранения в файл создать буффер:
```python
from io import BytesIO

...

buffer_ = BytesIO()
plt.savefig(buffer_, bbox_inches = 'tight', dpi=80)
buffer_.seek(0)
return buffer_
```
А в файле `stat_menu.py`, где происходит загрузка картинки вместо файла брать возвращаемое значение из функции histogram:
```python
image = pygame.image.load(histogramm())
```

**Comment by BerezkinNick** [comment]
Спасибо. Уже успешно реализовано.
