### ISSUE TITLE
Комментарии и предложения

### ISSUE THREAD

**Issue by Godofnothing** [Pygame-Tetris-2020/tetris-2020#13]
Реализовано очень красиво - разные темы, красивая менюшка с падающими блоками. 

Звук лично у меня работает нормально, хорошо, что есть возможность выбирать разные темы. 

Очень качественный `README.md`

Пару пожеланий по структуре проекта 
- У вас довольно много файлов  `.py` - для больше порядка и структуры разложите по папкам структурно идентичные файлы. Например `cube.py`, `figure.py` можно сложить в отдельную папку - `objects`, или как вам угодно назвать. 
- Файлы кэшей лучше не добавлять в репозиторий

**Comment by Ivan-Ivashkin** [comment]
Здравствуйте!
Спасибо за комментарий. Репозиторий структурируем, когда завершим работу над содержательной частью проекта.
