### ISSUE TITLE
Проблема со звуком

### ISSUE THREAD

**Issue by kol060k** [Pygame-Tetris-2020/tetris-2020#14]
Ребят, а проблема со звуком точно решена?
У меня опять вылазят ошибки:
![image](https://user-images.githubusercontent.com/33592658/102001199-aad43a00-3d08-11eb-8509-d0079a01ba63.png)
Подозреваю, что дело в том, что хоть вы и конвертировали внутриигровые звуки в wav формат, но фоновая музыка осталась в mp3:
![image](https://user-images.githubusercontent.com/33592658/102001226-ea028b00-3d08-11eb-8e81-5c57015140f0.png)

**Comment by safin-dr** [comment]
Спасибо за комментарий! Постараемся исправить.

**Comment by safin-dr** [comment]
Проблема была исправлена. Теперь уже окончательно, я предполагаю. Спасибо, что помогаете нам становиться лучше!
