### ISSUE TITLE
Комментарии и предложения

### ISSUE THREAD

**Issue by kol060k** [Pygame-Tetris-2020/tetris-2020#15]
Ребята, наконец, игра запустилась, и я её посмотрел.
Сделано очень круто, мне нравится, я прямо позалипал! Оформление очень приятное, звуковые эффекты сделали хорошие!

Что можно поправить (до защиты лучше уже не мучайтесь):
1) Шрифт слова "Тёмная" в настройках, кажется, не такой, как на остальных кнопках.
2) Думаю, будет красивее, если границы стакана будут "за пределами поля". То есть чтобы когда тетрамино прижимается к краю, белая граница оставалась:
![image](https://user-images.githubusercontent.com/33592658/102024238-51bce280-3daa-11eb-9fbf-51f0403603cc.png)

Предложения, если будете доделывать игру после защиты проекта (до защиты уже не надо):
1) Реализуйте поворот фигурок у стенки со сдвигом их центра. Имею в виду, что чтобы повернуть палку у стенки тоже было можно (при этом её нужно отодвинуть на клетку):
![image](https://user-images.githubusercontent.com/33592658/102024378-1ff84b80-3dab-11eb-90e5-96cc63affe7a.png)
2) Увеличьте время до того, как тетрамино встаёт в положение намертво, чтобы их можно было задвинуть под стоящие выше фигуры. Приходится проявлять чудеса гипер таппинга, чтобы, например, провернуть вот это:
![image](https://user-images.githubusercontent.com/33592658/102024336-e0316400-3daa-11eb-9216-631e421dce80.png)
(если время до фиксирования фигурки выбрано оригинальным, а я просто проклятый казуал, то так и скажите :D)
Upd. Обнаружил, что если зажимать, то фигурки в принципе двигаются на 1 клеточку под другие до того, как приземлиться окончательно. А сдвиг на 2 бывает?
3) Предложение уровня про. Реализовать возможность не только некоторое время двигать тетрамино, когда они уже приземлились, но и возможность их поворота, если это не поднимает их центр вверх, как это сделал Джозеф в 2018:
![image](https://user-images.githubusercontent.com/33592658/102024579-56829600-3dac-11eb-95e3-98cc79b4df65.png)
1:52 вот тут: https://youtu.be/Gt9tWO0Zaxo?t=112

Ну а в целом, так держать! Вы молодцы! :)

**Comment by Ivan-Ivashkin** [comment]
Здравствуйте! Спасибо за подробный отзыв и советы. Отвечу по пунктам.

1. Шрифт во всей игре используется один и тот же. Кажущееся различие объясняется неодинаковым размером шрифта: он зависит от соотношения длины слова и кнопки. При более детальной проработке дизайна нам следовало бы исправить сторонний класс Button так, чтобы была возможность настраивать размер шрифта и центрировать текст по осям кнопки. Это переносим в разряд планов на будущее.

2. Баг с границами стакана для нас новинка. По-видимому, мы его не замечали, так как тестировали программу в основном на светлой теме. Вносим в список необходимых правок.

3. С вопросом о повороте фигур вблизи границ стакана мы тоже знакомы. При нынешней организации поворота реализовать подобное возможно введением специальных функций. Более изящное (но затратное в смысле времени и усилий) решение - полностью переписать метод поворота фигур. В настоящее время применяется словарь поворотов. При продвинутой реализации от словарей следовало бы перейти к расчетам.

4. Специальных ограничений на горизонтальное перемещение фигур, которые вот-вот остановятся, не введено. Всё определяется только задержкой между последовательными автоматическими опусканиями фигуры (сейчас выставлено на полсекунды, если не ошибаюсь). Теоретически возможно перемещение на произвольное число клеток при свободности пути и достаточной ловкости. Дело, по-видимому, еще и в чувствительности клавиатуры.

5. Здесь ситуация во многом схожа с описанной в пункте (3). Полагаю, эти проблемы следует решать совместно подбором более сложного метода поворота.
