### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by FrCln** [Pygame-Tetris-2020/tetris-2020#2]
Добавьте информацию в файл README.

Что в нем должно быть:

1. Общая информация о проекте - что он из себя представляет, зачем нужен, главные достоинства.

2. Инструкция по установке "для чайников":

   - установите python с сайта...

   - склонируйте репозиторий (*в итоговой версии нужно будет сделать релиз, чтобы не нужно было клонировать весь репозиторий, но пока можно и так*), это делается так-то...

   - запустите python main.py

3. Инструкция по использованию. Клавиши, управление, примеры (желательно добавить скриншоты), фичи.

4. Информация, куда писать предложения по улучшению или сообщения о багах (*в issues, конечно, куда же ещё*).

**Comment by Ivan-Ivashkin** [comment]
Информация в файл README внесена.
