### ISSUE TITLE
Как он здесь оказался?

### ISSUE THREAD

**Issue by FrCln** [Pygame-Tetris-2020/tetris-2020#4]
Фигура уехала за границы экрана и застряла. Обычно такого не происходит, но вот один раз так вышло. Разберитесь.
![Снимок экрана от 2020-12-04 21-33-12](https://user-images.githubusercontent.com/54150197/101201271-84fbc500-3678-11eb-8d2c-d5fbbdd05802.png)

**Comment by Ivan-Ivashkin** [comment]
Здравствуйте!

Спасибо за замечание! Данный баг был исправлен. Предварительная проверка показала, что он перестал воспроизводиться. Код будет вычитан повторно для более точной проверки.

**Comment by sarseniy** [comment]
Да кстати, этот я баг тоже встретил. Завтра попробую снова протестить)
