### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by sarseniy** [Pygame-Tetris-2020/tetris-2020#5]
Как и обещал в #4 тестирую снова.

На этот раз получил вот такую штуку во время игры.
![image](https://user-images.githubusercontent.com/70952998/101236619-6f2be580-36f4-11eb-846e-3536ec186a6c.png)
Попытаюсь разобраться, что произошло.

UPD: Спустя 20 минут тестов больше такого не встретил. Также посмотрел другую ветку. Там тоже этой ошибки не было. Но на всякий случай проверьте, что пошло не так. (во время игры я неистово крутил фигурку и перемещал её)

Ещё (не)много неприятно, что фигурку нельзя вращать, когда она соприкасается со "сторонами стакана" или с другими фигурками. Посмотрите, что можно сделать)

**Comment by Ivan-Ivashkin** [comment]
Спасибо за подробный отчет! Будем исправлять!

**Comment by Ivan-Ivashkin** [comment]
Баг предварительно исправлен. На протяжении последних трех дней работы над программой он не был замечен.
Совершенствование алгоритмов поворота фигуры продолжим в последующих версиях.
