### ISSUE TITLE
Проблемы с классом Button

### ISSUE THREAD

**Issue by safin-dr** [Pygame-Tetris-2020/tetris-2020#8]
![image](https://user-images.githubusercontent.com/71657422/101399795-0786bd80-38e1-11eb-88f9-9612380086a9.png)
После последнего коммита получается, что игра перестала функционировать дальше меню, сразу выходит ошибка, связанная с атрибутами класса Button

**Comment by Ivan-Ivashkin** [comment]
Ошибка была связана с неверным редактированием класса Button. Работоспособность класса восстановлена.
