### ISSUE TITLE
Комментарии и предложения

### ISSUE THREAD

**Issue by kol060k** [Pygame-Tetris-2020/tetris-2020#9]
Ещё не протестировал, проблема со звуком.
Система: виртуальная Ubuntu 18.04
Ошибка:
Рандомное число строчек `ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred`
А затем:
```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    curr_music.play()  # Запуск текущей музыки
  File "/home/kol060k/1kurs_python/tetris-2020/music.py", line 15, in play
    pygame.mixer.music.load(self.curr_music)
pygame.error: Unrecognized audio format
```
Как запустится, протестирую и отпишу.

---
Но уже до запуска есть несколько предложений.

Добавьте вычисление очков в зависимости от количества одновременно удалённых линий. Можно воспользоваться классическими правилами тетриса:
_1 линия — 100 очков, 2 линии — 300 очков, 3 линии — 700 очков, 4 линии (то есть, сделать Тетрис) — 1500 очков._
_http://www.cultin.ru/game-tetris_

Попробуйте добавить несколько скоростных уровней, чтобы фигурки увеличивали свою скорость по мере прохождения порога в N сбритых линий.

---
А можно премиум версию с комментариями Юрия?
Как выбрать скин Джонаса?
А будут вставки с анекдотами?
P.S. Было бы кощунственно разрабатывать тетрис и ни разу не видеть этот шедевр, но на всякий случай держите: https://www.youtube.com/watch?v=Gt9tWO0Zaxo

**Comment by Ivan-Ivashkin** [comment]
Здравствуйте!

Спасибо за отзыв! Отвечу по пунктам.

1. Проблема со звуковыми файлами в настоящее время решена: файлы конвертированы в формат, доступный для чтения в Pygame-ом. У студентов нашей команды программа теперь запускается без ошибок.

2. Подсчет очков реализован по предложенным Вами классическим правилам тетриса.

3. На этапе обсуждения задач проекта реализация ускорения фигур планировалась. Постараемся включить эту функцию, если успеем.

4.  Запись турнира мы видели. Она нас в известной степени и вдохновила. :)
